# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
